### PR TITLE
CAA Fixes

### PR DESCRIPTION
**Pull request by birgelee**
This merge incorporates changes that allow us to pass all CAA test suite cases.

### CODE REVIEW

**Comment by birgelee** [comment]
@sciros @gcimaszewski Unless there is objection, I think we should merge this branch into main given it is stable, accomplished the originally stated goal of improving CAA parsing, and it passes all integration and unit tests. Further improvements can be done on another branch dedicated to our next objective.

**Comment by birgelee** [comment]
The README is now updated to more accurately reflect the current state of the project.

**Comment by sciros** [comment]
Yep, feel free to merge it in. I'll see about spinning off a branch to look at the distance/RIR logic for building cohorts next. It _might_ end up being the same branch as retry logic since that's one of the main drivers for how cohorts are built.

**Comment by birgelee** [comment]
I like the idea of a new branch for RIR/distance logic which might also take into account retries.

**Pull request merged**
